server:
  port: 8080
  ssl:
    enabled: false  # Nếu sử dụng HTTPS, đổi thành true và thiết lập keystore

spring:
  security:
    oauth2:
      client:
        registration:
          wso2:
            client-id: cw7Ijw0Biv0fMJGKMtwd4ePof78a
            client-secret: 9h0ZBeHLrXIxV6qqvFqmsWW3kBJI7pLd3dk1jZbjxo8a
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            redirect-uri: "http://localhost:8080/login/oauth2/code/wso2"
        provider:
          wso2:
            authorization-uri: https://localhost:9443/oauth2/authorize
            token-uri: https://localhost:9443/oauth2/token
            user-info-uri: https://localhost:9443/oauth2/userinfo
            jwk-set-uri: https://localhost:9443/oauth2/jwks
            user-name-attribute: sub  # Hoặc "preferred_username" tùy theo WSO2
